const mongoose = require('mongoose');
const Map = require('../models/map');

const getUserMaps = async (req, res) => {
    try {
      const { email } = req.body;
  
      // Find maps generated by this user
      const userMaps = await Map.find({ userEmail: email });
  
      res.status(200).json(userMaps);
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  const deleteMap = async (req, res) => {
    try {
      const { id } = req.params;
      console.log("Received ID:", id); // Debug log
  
      if (!mongoose.Types.ObjectId.isValid(id)) {
        return res.status(400).json({ error: "Invalid map ID format" });
      }
  
      const map = await Map.findById(id);
      if (!map) {
        console.log("Map not found for ID:", id);
        return res.status(404).json({ error: "Map not found" });
      }
  
      await Map.findByIdAndDelete(id);
      console.log("Map deleted successfully:", id);
  
      res.status(200).json({ message: "Map deleted successfully" });
    } catch (error) {
      console.error("Error deleting map:", error);
      res.status(500).json({ error: "An unexpected error occurred" });
    }
  };
  
  
module.exports = { getUserMaps,deleteMap};
